:sectnums:

=== Section 2 (the definition of *Clubs Council*)

Add "and PARSA".

=== After Section 2

Insert:

====
++++
<h2>3. Objects</h2>
++++

The objects of the association are to encourage the study and practice of computer science, software engineering, and related fields by students of the ANU.
====

=== Subsection 3(1)

Omit ", the Clubs Council of ANUSA, and PARSA", substitute "and to Clubs Council".

=== Section 5

Omit "general representative" in all instances, substitute "ordinary committee member".

Omit "representative" in all other instances, substitite "officer".

=== Subsection 5(2)

Repeal the subsection, substitute:

====
[start=2]
. The committee may appoint up to 3 further ordinary committee members in addition to those mentioned in subsection 6(1).
====

=== Subsection 5(9)

Repeal the subsection, substitute:

====
[start=9]
. Decisions of the committee are made by motion passed by a majority of committee members present and voting at a meeting of the committee, or by motion passed by a majority of committee members circulated outside of a meeting.
====

=== Subsection 5(10)

Omit "and each member of the committee are", substitute "is".

=== Subsection 5(11)

Add "(other than this power of delegation) to any person or group of people.".

=== Subsection 6(8)

Repeal the subsection, substitute:

====
[start=8]
. If one or more candidates would be elected to more than one position, they are each elected to the position for which they nominated the highest preference, and each lower-preferenced position is re-determined as though those candidates withdrew.
+
This process is repeated as necessary.
====

=== Subsection 6(9)

Omit "successful", substitute "elected".

Add:

====
Any position not filled at an annual general meeting becomes vacant two weeks after the conclusion of the meeting.
====

=== Subsection 6(10)

Repeal the subsection.

=== After section 6

Insert:

====
++++
<h2>8. Committee — responsibilities</h2>
++++

. The treasurer must keep records of the income and expenditure of the association, and report on these to each annual general meeting.

. The secretary must keep minutes of --

.. elections and appointments of committee members; and

.. the names of committee members present at a committee meeting or student members present at a general meeting; and

.. proceedings of committee and general meetings.

. The secretary must keep in their custody all records (inclding minutes) of the association, and make these available for inspection upon the request of a member.
====

=== Subsection 8(2)

Repeal the subsection, substitute:

====
[start=2]
. A general meeting must be accessible to members, and must be held on ANU campus unless circumstances outside the control of the committee prevent this.
====

=== Subsection 8(3)

After "notify members", insert "by email".

=== Subsections 9(2) and 9(3)

Repeal the subsections.

=== Section 10

Repeal the section, substitute:

====
++++
<h2>12. Funds</h2>
++++
. Funds of the association may come from membership fees, grants or reimbursments from Clubs Council or any other organ of ANU, ANUSA, or PARSA, sponsorships by other organisations, and any other sources that the committee decides.

. Funds of the association may be used for the objects of the association in the way the committee decides.

. Funds of the association may be expended by the committee.

. The committee may allow a person to expend funds up to a particular amount not exceeding $500 for a particular purpose, or for a general purpose, without seeking approval from the committee for individual expenditures.

. Funds of the association must not be given directly or indirectly to members of the association except as bona fide compensation for services rendered or expenses incurred on behalf of the association.

. The financial year of the association ends on 30th June of each year.
====

=== Subsection 11(2)

Repeal the subsection, substitute:

====
[start=2]
. In the event of dissolution, any funds or property of the association remaining after all debts and liabilities are satisfied must be given to ANUSA.

. Members of the association are not liable to contribute to debts and liabilities of the association in the event of dissolution.
====
