= The Australian National University Computer Science Students' Association 2020 Annual General Meeting: Agenda
ANU CSSA <anucssa@anu.edu.au>
23 September 2020

:sectnums:
:xrefstyle: short

== Welcome

== Reports

=== President's Report

Refer to <<_presidents_report_2>>.

=== Treasurer's Report

Refer to <<_treasurers_report_2>>.

== Motions

=== Motion to amend the constitution

Moved by Felix.

Refer to <<_proposed_amendments_to_the_constitution>>.

== Election

== Other business

<<<

[appendix]
== President's Report

To be finalised - this document will be updated 2020-09-22.

<<<

[appendix]
== Treasurer's Report

:sectnums!:

=== Introduction

The CSSA has had a massive surplus this financial year, due mostly to COVID-19 related
effects. The CSSA has reached a surplus of $8123.67 for this financial year as a result.

=== Xero

The CSSA Committee has invested in a subscription to Xero to aid in managing the
CSSA’s books. This has lead to easier budgeting, reporting and accountability for
transactions. New procedures were implemented by the committee to ensure sufficient
paper trail for all transactions and to ensure there were no misappropriation of funds.
These new procedures have worked immensely well, with the committee being informed of
financial status regularly.

=== Memberships

The CSSA has seen a downturn in membership purchases this calendar year, which we
believe is due to COVID-19. Without CSSA events and the common room being
accessible, we have been unable to sell as many memberships as we would in previous
years. A membership app has been developed (https://members.cssa.club) which allows
members to purchase a membership online via Visa/Mastercard, which has seen a few
memberships sold since the in-person stream became unavailable. The EFTPOS payment
facility charges the CSSA a small fee per transaction, which we split with the member –
typically a fee is approx 39c, and we charge the member an additional 20c fee.

=== Revenue/Income

The CSSA Industry Portfolio has received a much larger income this year with a new
industry representative. Due to COVID-19, fewer industry events have been run,
increasing our industry related surplus.

The CSSA has entered into a sponsorship with CECS, to provide funding of study events
to expenses including catering etc. This agreement was made before campus closure, and
study event expenses were reduced greatly by performing them online via video streaming
platforms.

=== Vending Machines

The vending machine income dropped sharply at the end of the financial year as the
committee decided to disable all of the vending machine fleet to prevent them becoming
high-touch areas, shortly before the campus closed.

As of today, the vending machine fleet remains out of service. We currently intend to
restore the fleet back into operation next calendar year.

This year, the vending machines produced an income of $7962.10 with cost of goods sold
of $4180.39 for an average profit margin of 90.5%. Expenses on the vending machine fleet
included re-keying the machines ($96.60). Funds for the purchase of a cart to move stock
was kindly donated by Jane Street to the value of $199.

=== Expenses

With the campus remaining closed, the CSSA has seen a lower rate of expenditure, due to
fewer events (both academic and industry), no Epic Games night, no careers fair and a
virtual pause on upkeep of the common room.

Typically the CSSA does not see such a high surplus, but this can be attributed to the
greatly increased income and greatly decreased expenses.

////
=== References

link:2020-06-30-surplus-deficit.pdf[Surplus and Deficit]

link:2020-06-30-balance-sheet.pdf[Balance Sheet]
////

<<<

////
.Surplus and Deficit
[cols=",>",grid=none]
|===

2+h|Trading Income

|Donations|249.00

|Event Ticket Sales|169.99

|Industry Sponsorships|3,500.00

|Memberships|880.00

|Vending Sales|7,962.10

e|Total Trading Income
e|12,761.09

2+h|Other Income

|ANU Union Commission|427.07

|ANUSA Events Grants|5,934.88

|EFTPOS Fees|25.30

|CECS Funding|2,010.00

e|Total Other Income
e|8,397.25

s|Gross Income
s|21,158.34

2+h|Cost of Sales

|Vending Cost of Goods Sold|4,180.39

e|Total Cost of Sales
e|4,180.39

2+h|Operating Expenses

|Advertising|896.83

|Common Room Expense|612.02

|Xero|536.28

|Event Catering

|5,682.45

|Event Expenses

|744.66

|General Expenses|55.00

|Stripe Fees|33.44

|Vending Expenses|293.60

e|Total Operating Expenses
e|8,854.28

s|Net Surplus/(Deficit)
s|8,123.67
////

////
== Balance Sheet

As at 30 June 2020

Assets::
Bank:::
CSSA 2 to sign:::: 8,376.39
CSSA Transactions:::: 94.99
Total Bank:::: 8,471.38
Total Assets::: 8,471.38
Liabilities::
Current Liabilities:::
Reimbursements Payable:::: 21.10
Total Current Liabilities:::: 21.10
Total Liabilities::: 21.10
Net Assets:: 8,450.28
Equity::
Current Year Earnings:::
8,123.67
Retained Earnings:::
326.61
Total Equity:::
8,450.28
////

[appendix]
== Proposed amendments to the constitution

:sectnums:

=== Section 2 (the definition of *Clubs Council*)

Add "and PARSA".

=== After Section 2

Insert:

====
[discrete]
== 3. Objects

The objects of the association are to encourage the study and practice of computer science, software engineering, and related fields by students of the ANU.
====

=== Subsection 3(1)

Omit ", the Clubs Council of ANUSA, and PARSA", substitute "and to Clubs Council".

=== Section 5

Omit "general representative" in all instances, substitute "ordinary committee member".

Omit "representative" in all other instances, substitite "officer".

=== Subsection 5(2)

Repeal the subsection, substitute:

====
[start=2]
. The committee may appoint up to 3 further ordinary committee members in addition to those mentioned in subsection 6(1).
====

=== Subsection 5(9)

Repeal the subsection, substitute:

====
[start=9]
. Decisions of the committee are made by motion passed by a majority of committee members present and voting at a meeting of the committee, or by motion passed by a majority of committee members circulated outside of a meeting.
====

=== Subsection 5(10)

Omit "and each member of the committee are", substitute "is".

=== Subsection 5(11)

Add "(other than this power of delegation) to any person or group of people.".

=== Subsection 6(8)

Repeal the subsection, substitute:

====
[start=8]
. If one or more candidates would be elected to more than one position, they are each elected to the position for which they nominated the highest preference, and each lower-preferenced position is re-determined as though those candidates withdrew.
+
This process is repeated as necessary.
====

=== Subsection 6(9)

Omit "successful", substitute "elected".

Add:

====
Any position not filled at an annual general meeting becomes vacant two weeks after the conclusion of the meeting.
====

=== Subsection 6(10)

Repeal the subsection.

=== After section 6

Insert:

====
[discrete]
== 8. Committee — responsibilities

. The treasurer must keep records of the income and expenditure of the association, and report on these to each annual general meeting.

. The secretary must keep minutes of --

.. elections and appointments of committee members; and

.. the names of committee members present at a committee meeting or student members present at a general meeting; and

.. proceedings of committee and general meetings.

. The secretary must keep in their custody all records (inclding minutes) of the association, and make these available for inspection upon the request of a member.
====

=== Subsection 8(2)

Repeal the subsection, substitute:

====
[start=2]
. A general meeting must be accessible to members, and must be held on ANU campus unless circumstances outside the control of the committee prevent this.
====

=== Subsection 8(3)

After "notify members", insert "by email".

=== Subsections 9(2) and 9(3)

Repeal the subsections.

=== Section 10

Repeal the section, substitute:

====
[discrete]
== 12. Funds

. Funds of the association may come from membership fees, grants or reimbursments from Clubs Council or any other organ of ANU, ANUSA, or PARSA, sponsorships by other organisations, and any other sources that the committee decides.

. Funds of the association may be used for the objects of the association in the way the committee decides.

. Funds of the association may be expended by the committee.

. The committee may allow a person to expend funds up to a particular amount not exceeding $500 for a particular purpose, or for a general purpose, without seeking approval from the committee for individual expenditures.

. Funds of the association must not be given directly or indirectly to members of the association except as bona fide compensation for services rendered or expenses incurred on behalf of the association.

. The financial year of the association ends on 30th June of each year.
====

=== Subsection 11(2)

Repeal the subsection, substitute:

====
[start=2]
. In the event of dissolution, any funds or property of the association remaining after all debts and liabilities are satisfied must be given to ANUSA.

. Members of the association are not liable to contribute to debts and liabilities of the association in the event of dissolution.
====
